name: Unzip Images

on:
  push:
    paths:
      - images.zip

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip images.zip
        run: |
          unzip -o images.zip -d .
          rm images.zip

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped images.zip"
          git push
